# FILE: src/agent_sommelier/tasks/storage.py
# PURPOSE: Abstract storage backend and two implementations (monolithic YAML, per-task YAML) for task persistence.
# OWNS: TaskStorage ABC, MonolithicYamlStorage, PerFileYamlStorage, path constants, YAML headers, storage version detection.
# EXPORTS: TaskStorage, MonolithicYamlStorage, PerFileYamlStorage, TASKS_DIR_NAME, TASKS_FILE_NAME, CLOSED_FILE_NAME, TASKS_HEADER, CLOSED_HEADER, STORAGE_VERSION, META_FILE_NAME, detect_storage_version.
# DOCS: docs/arch.md

from __future__ import annotations

import re
from abc import ABC, abstractmethod
from pathlib import Path
from typing import Any

import yaml

# ---------------------------------------------------------------------------
# Constants
# ---------------------------------------------------------------------------

STORAGE_VERSION = 2
TASKS_DIR_NAME = ".agents/tasks"
META_FILE_NAME = "meta.yaml"
TASKS_FILE_NAME = "tasks.yaml"
CLOSED_FILE_NAME = "closed.yaml"
INBOX_FILE_NAME = "inbox.md"

_TASK_FILE_RE = re.compile(r"^TSK-\d{4}\.yaml$")

# ---------------------------------------------------------------------------
# File headers — written to the top of each YAML file when saved
# ---------------------------------------------------------------------------

TASKS_HEADER = """\
# ======================================================================
# Agent Sommelier Task System — Active Task List
# ======================================================================
#
# !! DO NOT EDIT THIS FILE DIRECTLY !!
# Use the `tasks` CLI tool to manage tasks.
# Manual edits will be overwritten. If the file is broken, run
# `tasks init` to repair it, then re-add missing tasks via the CLI.
#
# Commands:
#   tasks init              Bootstrap or repair task files
#   tasks add "Title"       Create a new task
#   tasks list              Show active tasks
#   tasks show TSK-NNNN     Full detail of one task
#   tasks take TSK-NNNN     Mark a task in-progress (shorthand)
#   tasks update TSK-NNNN   Modify a task
#   tasks close TSK-NNNN    Close a task (any status)
#   tasks next              Highest-priority todo(s)
#   tasks status            Session overview
#   tasks history           Recently completed tasks
#   tasks inbox             Print inbox.md
#   tasks search <text>     Full-text search across all tasks
#   tasks --help            Full documentation
#
# Statuses:  configurable in meta.config at top of this file
# Closed:    tasks close TSK-NNNN  or  tasks update --closed
# Priority:  p0 (critical) > p1 > p2 > p3 > p4 (backlog)
# Newest at top, oldest at bottom.
# ======================================================================

"""

CLOSED_HEADER = """\
# ======================================================================
# Agent Sommelier Task System — Closed Task Archive
# ======================================================================
#
# !! DO NOT EDIT THIS FILE DIRECTLY !!
# Use `tasks close TSK-NNNN` to close a task. Run `tasks update --closed`
# to archive with a specific status. Manual edits will be overwritten.
#
# Append-only — nothing is ever deleted from this file.
# Newest at bottom, oldest at top (chronological).
#
# Run `tasks history` to view closed tasks.
# ======================================================================

"""


# ---------------------------------------------------------------------------
# Version detection
# ---------------------------------------------------------------------------


def detect_storage_version(tasks_dir: Path) -> int:
    """Detect which storage format version exists at tasks_dir.

    Returns 2 if meta.yaml exists (per-file format).
    Returns 1 if tasks.yaml exists without meta.yaml (monolithic format).
    Returns 2 for fresh init (no files exist).
    """
    meta_path = tasks_dir / META_FILE_NAME
    tasks_path = tasks_dir / TASKS_FILE_NAME
    if meta_path.exists():
        try:
            raw = yaml.safe_load(meta_path.read_text(encoding="utf-8"))
            if isinstance(raw, dict):
                return raw.get("version", 2)
        except Exception:
            pass
        return 2
    if tasks_path.exists():
        return 1
    return 2  # fresh init, use per-file


# ---------------------------------------------------------------------------
# Abstract base class
# ---------------------------------------------------------------------------


class TaskStorage(ABC):
    """Pluggable interface for task persistence."""

    @abstractmethod
    def load_meta(self) -> dict[str, Any]:
        """Load metadata dict (counter, config)."""

    @abstractmethod
    def save_meta(self, meta: dict[str, Any]) -> None:
        """Persist metadata dict."""

    @abstractmethod
    def load_all_tasks(self) -> list[dict[str, Any]]:
        """Load all tasks (active + closed)."""

    @abstractmethod
    def get_task(self, task_id: str) -> dict[str, Any] | None:
        """Retrieve a single task by ID, or None."""

    @abstractmethod
    def save_task(self, task: dict[str, Any]) -> None:
        """Persist or update a single task."""

    @abstractmethod
    def delete_task(self, task_id: str) -> None:
        """Remove a task by ID."""

    @abstractmethod
    def init_storage(self, meta: dict[str, Any]) -> None:
        """Initialize empty storage with given meta."""

    @abstractmethod
    def storage_type(self) -> str:
        """Return a human-readable storage type identifier."""

    @abstractmethod
    def deinit_storage(self) -> None:
        """Clean up for migration (e.g., rename old files to .bak)."""


# ---------------------------------------------------------------------------
# Monolithic implementation (version 1 — legacy)
# ---------------------------------------------------------------------------


class MonolithicYamlStorage(TaskStorage):
    """Storage backend that reads/writes tasks.yaml + closed.yaml as a pair."""

    def __init__(self, tasks_dir: Path) -> None:
        self._tasks_dir = tasks_dir
        self._tasks_file = tasks_dir / TASKS_FILE_NAME
        self._closed_file = tasks_dir / CLOSED_FILE_NAME

    # -- helpers -----------------------------------------------------------

    @staticmethod
    def _read_yaml(path: Path) -> Any:
        if not path.exists():
            return None
        return yaml.safe_load(path.read_text(encoding="utf-8"))

    @staticmethod
    def _write_yaml(path: Path, data: Any, header: str) -> None:
        path.parent.mkdir(parents=True, exist_ok=True)
        content = header + yaml.safe_dump(data, default_flow_style=False, sort_keys=False, allow_unicode=True)
        path.write_text(content, encoding="utf-8")

    @staticmethod
    def _extract_tasks(raw: Any) -> list[dict[str, Any]]:
        if isinstance(raw, dict):
            return raw.get("tasks", [])
        if isinstance(raw, list):
            return raw
        return []

    @staticmethod
    def _extract_meta(raw: Any) -> dict[str, Any]:
        if isinstance(raw, dict):
            return raw.get("meta", {})
        return {}

    # -- public interface --------------------------------------------------

    def load_meta(self) -> dict[str, Any]:
        raw = self._read_yaml(self._tasks_file)
        if raw is None:
            return {}
        return self._extract_meta(raw)

    def save_meta(self, meta: dict[str, Any]) -> None:
        raw = self._read_yaml(self._tasks_file)
        tasks = self._extract_tasks(raw) if raw is not None else []
        data: dict[str, Any] = {"meta": meta, "tasks": tasks}
        self._write_yaml(self._tasks_file, data, TASKS_HEADER)

    def load_all_tasks(self) -> list[dict[str, Any]]:
        result: list[dict[str, Any]] = []
        # Active tasks
        raw = self._read_yaml(self._tasks_file)
        if raw is not None:
            result.extend(self._extract_tasks(raw))
        # Closed tasks
        raw = self._read_yaml(self._closed_file)
        if raw is not None:
            result.extend(self._extract_tasks(raw))
        return result

    def get_task(self, task_id: str) -> dict[str, Any] | None:
        all_tasks = self.load_all_tasks()
        for t in all_tasks:
            if t.get("id") == task_id:
                return t
        return None

    def save_task(self, task: dict[str, Any]) -> None:
        task_id = task.get("id", "")
        # Read the active tasks file (all tasks live in a single unified list)
        tasks_raw = self._read_yaml(self._tasks_file)
        tasks_list = self._extract_tasks(tasks_raw) if tasks_raw is not None else []

        # Remove from tasks list (in case of overwrite)
        tasks_list = [t for t in tasks_list if t.get("id") != task_id]
        tasks_list.append(task)

        # Write active file
        tasks_meta = self._extract_meta(tasks_raw) if tasks_raw is not None else {}
        tasks_data: dict[str, Any] = {"meta": tasks_meta, "tasks": tasks_list}
        self._write_yaml(self._tasks_file, tasks_data, TASKS_HEADER)

    def delete_task(self, task_id: str) -> None:
        tasks_raw = self._read_yaml(self._tasks_file)
        closed_raw = self._read_yaml(self._closed_file)

        tasks_list = self._extract_tasks(tasks_raw) if tasks_raw is not None else []
        closed_list = self._extract_tasks(closed_raw) if closed_raw is not None else []

        tasks_list = [t for t in tasks_list if t.get("id") != task_id]
        closed_list = [t for t in closed_list if t.get("id") != task_id]

        tasks_meta = self._extract_meta(tasks_raw) if tasks_raw is not None else {}
        closed_meta = self._extract_meta(closed_raw) if closed_raw is not None else {}
        if not isinstance(closed_meta, dict):
            closed_meta = {}
        closed_meta["total_closed"] = len(closed_list)

        tasks_data: dict[str, Any] = {"meta": tasks_meta, "tasks": tasks_list}
        closed_data: dict[str, Any] = {"meta": closed_meta, "tasks": closed_list}
        self._write_yaml(self._tasks_file, tasks_data, TASKS_HEADER)
        self._write_yaml(self._closed_file, closed_data, CLOSED_HEADER)

    def init_storage(self, meta: dict[str, Any]) -> None:
        self._tasks_dir.mkdir(parents=True, exist_ok=True)
        data: dict[str, Any] = {"meta": meta, "tasks": []}
        self._write_yaml(self._tasks_file, data, TASKS_HEADER)
        closed_data: dict[str, Any] = {"meta": {"total_closed": 0}, "tasks": []}
        self._write_yaml(self._closed_file, closed_data, CLOSED_HEADER)

    def storage_type(self) -> str:
        return "monolithic"

    def deinit_storage(self) -> None:
        if self._tasks_file.exists():
            self._tasks_file.rename(self._tasks_file.with_suffix(".yaml.bak"))
        if self._closed_file.exists():
            self._closed_file.rename(self._closed_file.with_suffix(".yaml.bak"))


# ---------------------------------------------------------------------------
# Per-file implementation (version 2 — current)
# ---------------------------------------------------------------------------


class PerFileYamlStorage(TaskStorage):
    """Storage backend that writes one TSK-xxxx.yaml file per task plus meta.yaml."""

    def __init__(self, tasks_dir: Path) -> None:
        self._tasks_dir = tasks_dir
        self._meta_file = tasks_dir / META_FILE_NAME

    def _task_path(self, task_id: str) -> Path:
        return self._tasks_dir / f"{task_id}.yaml"

    def load_meta(self) -> dict[str, Any]:
        if not self._meta_file.exists():
            return {}
        raw = yaml.safe_load(self._meta_file.read_text(encoding="utf-8"))
        if isinstance(raw, dict):
            return raw
        return {}

    def save_meta(self, meta: dict[str, Any]) -> None:
        self._tasks_dir.mkdir(parents=True, exist_ok=True)
        meta["version"] = STORAGE_VERSION
        content = yaml.safe_dump(meta, default_flow_style=False, sort_keys=False, allow_unicode=True)
        self._meta_file.write_text(content, encoding="utf-8")

    def load_all_tasks(self) -> list[dict[str, Any]]:
        if not self._tasks_dir.exists():
            return []
        result: list[dict[str, Any]] = []
        for path in sorted(self._tasks_dir.iterdir()):
            if not _TASK_FILE_RE.match(path.name):
                continue
            try:
                raw = yaml.safe_load(path.read_text(encoding="utf-8"))
                if isinstance(raw, dict):
                    result.append(raw)
            except Exception:
                continue
        return result

    def get_task(self, task_id: str) -> dict[str, Any] | None:
        path = self._task_path(task_id)
        if not path.exists():
            return None
        try:
            raw = yaml.safe_load(path.read_text(encoding="utf-8"))
            if isinstance(raw, dict):
                return raw
        except Exception:
            pass
        return None

    def save_task(self, task: dict[str, Any]) -> None:
        self._tasks_dir.mkdir(parents=True, exist_ok=True)
        task_id = task.get("id", "")
        path = self._task_path(task_id)
        content = yaml.safe_dump(task, default_flow_style=False, sort_keys=False, allow_unicode=True)
        path.write_text(content, encoding="utf-8")

    def delete_task(self, task_id: str) -> None:
        path = self._task_path(task_id)
        if path.exists():
            path.unlink(missing_ok=True)

    def init_storage(self, meta: dict[str, Any]) -> None:
        self._tasks_dir.mkdir(parents=True, exist_ok=True)
        meta["version"] = STORAGE_VERSION
        content = yaml.safe_dump(meta, default_flow_style=False, sort_keys=False, allow_unicode=True)
        self._meta_file.write_text(content, encoding="utf-8")

    def storage_type(self) -> str:
        return "perfile"

    def deinit_storage(self) -> None:
        pass  # No monolithic files to clean up
