"""Task management CLI for AI agents.

Statuses: todo, in-progress, done, blocked, postponed, cancelled,
          review, waiting, parked, deferred, backlog, abandoned

Priorities: p0 (critical) > p1 > p2 > p3 > p4 (backlog)
Deps: blocks, parent, child, discovered, relates

Usage:
    tasks init              # Bootstrap task files
    tasks next              # Show highest-priority todo
    tasks list              # List active tasks
    tasks show TSK-0001     # Full detail of one task
    tasks history           # Recently completed tasks
    tasks status            # Session overview
    tasks add "Title"       # Create a task
    tasks update TSK-0001   # Modify a task
    tasks close TSK-0001    # Close a task (any status)
    tasks inbox             # Print inbox contents
    tasks search <text>     # Full-text search across all tasks
    tasks deps TSK-0001     # Show dependency graph
    tasks ready             # Top-priority unblocked todos
    tasks blocked           # Show blocked tasks with blockers
"""

from __future__ import annotations

import os
import sys
from datetime import datetime
from pathlib import Path
from typing import Any

import click
import yaml
from rich.console import Console
from rich.table import Table

# ---------------------------------------------------------------------------
# Constants
# ---------------------------------------------------------------------------

TASKS_DIR_NAME = "tasks"
INBOX_FILE_NAME = "inbox.md"
TASKS_FILE_NAME = "tasks.yaml"
CLOSED_FILE_NAME = "closed.yaml"

VALID_STATUSES = {
    "todo", "in-progress", "done",           # core lifecycle
    "blocked", "postponed", "cancelled",      # deferral / termination
    "review", "waiting",                      # handoff / gate
    "parked", "deferred", "backlog",           # triage / queue
    "abandoned",                               # dead end
}
VALID_PRIORITIES = {0, 1, 2, 3, 4}
VALID_SOURCES = {"inbox", "audit", "test", "jira", "agent", "idea"}

VALID_DEP_TYPES = {"blocks", "parent", "child", "discovered", "relates"}

PRIORITY_ORDER = {0: 0, 1: 1, 2: 2, 3: 3, 4: 4}
PRIORITY_LABELS = {0: "p0", 1: "p1", 2: "p2", 3: "p3", 4: "p4"}
# Map old named priorities to numeric for backwards compat
_NAMED_PRIORITY_MAP = {"urgent": 0, "high": 1, "medium": 2, "low": 3}
# Reverse map for CLI convenience aliases
_PRIORITY_ALIASES = {"critical": 0, "urgent": 0, "high": 1, "medium": 2, "low": 3, "backlog": 4,
                     "p0": 0, "p1": 1, "p2": 2, "p3": 3, "p4": 4}

# ---------------------------------------------------------------------------
# File headers — written to the top of each YAML file when saved
# ---------------------------------------------------------------------------

TASKS_HEADER = """\
# ======================================================================
# AgentCLI Task System — Active Task List
# ======================================================================
#
# !! DO NOT EDIT THIS FILE DIRECTLY !!
# Use the `tasks` CLI tool to manage tasks.
# Manual edits will be overwritten. If the file is broken, run
# `tasks init` to repair it, then re-add missing tasks via the CLI.
#
# Commands:
#   tasks init              Bootstrap or repair task files
#   tasks add "Title"       Create a new task
#   tasks list              Show active tasks
#   tasks show TSK-NNNN     Full detail of one task
#   tasks update TSK-NNNN   Modify a task
#   tasks close TSK-NNNN    Close a task (any status)
#   tasks next              Highest-priority todo(s)
#   tasks status            Session overview
#   tasks history           Recently completed tasks
#   tasks inbox             Print inbox.md
#   tasks search <text>     Full-text search across all tasks
#   tasks --help            Full documentation
#
# Statuses:  todo, in-progress, done, blocked, postponed, cancelled,
#            review, waiting, parked, deferred, backlog, abandoned
# Closed:    tasks close TSK-NNNN  or  tasks update --closed
# Priority:  p0 (critical) > p1 > p2 > p3 > p4 (backlog)
# Newest at top, oldest at bottom.
# ======================================================================

"""

CLOSED_HEADER = """\
# ======================================================================
# AgentCLI Task System — Closed Task Archive
# ======================================================================
#
# !! DO NOT EDIT THIS FILE DIRECTLY !!
# Use `tasks close TSK-NNNN` to close a task. Run `tasks update --closed`
# to archive with a specific status. Manual edits will be overwritten.
#
# Append-only — nothing is ever deleted from this file.
# Newest at bottom, oldest at top (chronological).
#
# Run `tasks history` to view closed tasks.
# ======================================================================

"""


# ---------------------------------------------------------------------------
# Path resolution
# ---------------------------------------------------------------------------


def _resolve_tasks_dir() -> Path:
    """Find or default to the tasks/ directory relative to cwd."""
    cwd = Path.cwd()
    tasks_dir = cwd / TASKS_DIR_NAME
    return tasks_dir


def _tasks_file() -> Path:
    return _resolve_tasks_dir() / TASKS_FILE_NAME


def _inbox_file() -> Path:
    return _resolve_tasks_dir() / INBOX_FILE_NAME


# ---------------------------------------------------------------------------
# YAML file I/O
# ---------------------------------------------------------------------------


def _migrate_task(task: dict[str, Any]) -> dict[str, Any]:
    """Apply all migrations to a single task dict. Mutates and returns it."""
    return _ensure_deps_normalized(task)


def _migrate_tasks(tasks: list[dict[str, Any]]) -> list[dict[str, Any]]:
    """Apply all migrations to every task in a list."""
    for t in tasks:
        _migrate_task(t)
    return tasks


def load_tasks_yaml() -> tuple[dict[str, Any], list[dict[str, Any]]]:
    """Load tasks.yaml. Returns (meta, tasks_list).

    If file does not exist, raises FileNotFoundError.
    If YAML is malformed, raises yaml.YAMLError.
    If file exists but is empty or has unexpected structure, returns defaults.

    Auto-migrates legacy 'related' fields to 'deps' list and named priorities
    to numeric on load.
    """
    path = _tasks_file()
    if not path.exists():
        raise FileNotFoundError(f"Tasks file not found: {path}\nRun 'tasks init' first.")

    raw = yaml.safe_load(path.read_text(encoding="utf-8")) or {}
    meta = raw.get("meta", {})
    if not isinstance(meta, dict):
        meta = {}
    tasks = raw.get("tasks", [])
    if not isinstance(tasks, list):
        tasks = []
    _migrate_tasks(tasks)
    return meta, tasks


def save_tasks_yaml(meta: dict[str, Any], tasks: list[dict[str, Any]]) -> None:
    """Write tasks.yaml with meta and tasks list.

    Tasks are stored newest-first (by 'created' descending).
    Missing optional fields are excluded from output.
    """
    path = _tasks_file()
    path.parent.mkdir(parents=True, exist_ok=True)
    data: dict[str, Any] = {"meta": meta, "tasks": _strip_none_fields_from_list(tasks)}
    content = TASKS_HEADER + yaml.safe_dump(data, default_flow_style=False, sort_keys=False,
                                             allow_unicode=True)
    path.write_text(content, encoding="utf-8")


def load_closed_yaml() -> list[dict[str, Any]]:
    """Load closed.yaml. Returns list of closed tasks.

    Handles the {meta, tasks} format.
    Falls back to legacy done.yaml if closed.yaml doesn't exist.
    Returns [] if neither file exists.

    Auto-migrates legacy fields on load.
    """
    path = _resolve_tasks_dir() / CLOSED_FILE_NAME
    if not path.exists():
        old_path = _resolve_tasks_dir() / "done.yaml"
        if old_path.exists():
            raw = yaml.safe_load(old_path.read_text(encoding="utf-8")) or []
            if isinstance(raw, dict):
                tasks = raw.get("tasks", [])
            else:
                tasks = raw if isinstance(raw, list) else []
            _migrate_tasks(tasks)
            return tasks
        return []
    raw = yaml.safe_load(path.read_text(encoding="utf-8")) or []
    if isinstance(raw, dict):
        tasks = raw.get("tasks", [])
    else:
        tasks = raw if isinstance(raw, list) else []
    _migrate_tasks(tasks)
    return tasks


def save_closed_yaml(closed_list: list[dict[str, Any]]) -> None:
    """Write closed.yaml with meta wrapper and header.

    Oldest-first (chronological order). Meta tracks total_closed counter.
    """
    path = _resolve_tasks_dir() / CLOSED_FILE_NAME
    path.parent.mkdir(parents=True, exist_ok=True)
    meta = {"total_closed": 0}
    if path.exists():
        existing_raw = yaml.safe_load(path.read_text(encoding="utf-8")) or {}
        if isinstance(existing_raw, dict):
            meta = existing_raw.get("meta", meta)
    meta["total_closed"] = len(closed_list)
    data = {"meta": meta, "tasks": _strip_none_fields_from_list(closed_list)}
    content = CLOSED_HEADER + yaml.safe_dump(data, default_flow_style=False, sort_keys=False,
                                              allow_unicode=True)
    path.write_text(content, encoding="utf-8")


def load_inbox() -> str:
    """Read inbox.md contents. Returns empty string if file doesn't exist."""
    path = _inbox_file()
    if not path.exists():
        return ""
    return path.read_text(encoding="utf-8")


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------


def _strip_none_fields(task: dict[str, Any]) -> dict[str, Any]:
    """Return a new dict with only non-None values and non-empty collections."""
    result = {}
    for k, v in task.items():
        if v is None:
            continue
        if v == "":
            continue
        if isinstance(v, (list, dict)) and not v:
            continue
        # Skip legacy fields no longer in use
        if k in ("related",):
            continue
        result[k] = v
    return result


def _strip_none_fields_from_list(tasks: list[dict[str, Any]]) -> list[dict[str, Any]]:
    return [_strip_none_fields(t) for t in tasks]


def _now_date() -> str:
    """Return today's date as YYYY-MM-DD."""
    return datetime.now().strftime("%Y-%m-%d")


def _now_iso() -> str:
    """Return current ISO 8601 timestamp."""
    return datetime.now().isoformat()


def _format_id(counter: int) -> str:
    """Format a counter integer into TSK-NNNN ID."""
    return f"TSK-{counter:04d}"


def _normalize_priority(priority: Any) -> int | None:
    """Convert old named priority to int, pass through ints. Returns None for bad values."""
    if priority is None:
        return None
    if isinstance(priority, int):
        return priority if priority in PRIORITY_ORDER else None
    if isinstance(priority, str):
        # Try named alias first, then int parse
        mapped = _PRIORITY_ALIASES.get(priority.lower())
        if mapped is not None:
            return mapped
        try:
            val = int(priority)
            return val if val in PRIORITY_ORDER else None
        except (ValueError, TypeError):
            return None
    return None


def _format_priority(priority: Any) -> str:
    """Format a priority value for display."""
    norm = _normalize_priority(priority)
    if norm is None:
        return "-"
    return PRIORITY_LABELS.get(norm, str(norm))


def _priority_sort_key(task: dict[str, Any]) -> int:
    """Return sort weight for priority (lower = higher priority)."""
    p = _normalize_priority(task.get("priority"))
    return p if p is not None else 99


def _ensure_deps_normalized(task: dict[str, Any]) -> dict[str, Any]:
    """Migrate old 'related' field to new 'deps' list format. Mutates and returns the task."""
    # Migrate old named priority to numeric
    old_p = task.get("priority")
    if old_p is not None and isinstance(old_p, str):
        new_p = _normalize_priority(old_p)
        if new_p is not None:
            task["priority"] = new_p

    # Migrate old related field to deps
    related = task.get("related")
    if related and not task.get("deps"):
        _ensure_deps_field(task)
        task["deps"].append({"id": str(related), "type": "relates"})
    # Remove old related field
    task.pop("related", None)
    # Remove empty deps
    deps = task.get("deps")
    if deps is not None and not deps:
        task.pop("deps", None)
    return task


def _ensure_deps_field(task: dict[str, Any]) -> list[dict[str, str]]:
    """Ensure task has a 'deps' list field. Returns the deps list."""
    if "deps" not in task or task["deps"] is None:
        task["deps"] = []
    elif not isinstance(task["deps"], list):
        task["deps"] = []
    return task["deps"]


def _get_dep_ids(task: dict[str, Any], dep_type: str | None = None) -> list[str]:
    """Get dep IDs optionally filtered by type."""
    deps = task.get("deps") or []
    if not isinstance(deps, list):
        return []
    if dep_type:
        return [d["id"] for d in deps if isinstance(d, dict) and d.get("type") == dep_type]
    return [d["id"] for d in deps if isinstance(d, dict)]


def _find_task_by_id(tasks: list[dict[str, Any]], task_id: str) -> dict[str, Any] | None:
    """Find a task by its 'id' field. Returns None if not found."""
    for t in tasks:
        if t.get("id") == task_id:
            return t
    return None


def _resolve_related(task_id: str, tasks_yaml: list[dict[str, Any]],
                     closed_yaml: list[dict[str, Any]]) -> dict[str, Any] | None:
    """Look up a task by ID in both active and closed lists. Returns the task dict or None."""
    found = _find_task_by_id(tasks_yaml, task_id)
    if found:
        return found
    return _find_task_by_id(closed_yaml, task_id)


def _get_blockers(task: dict[str, Any], tasks_list: list[dict[str, Any]],
                  closed_list: list[dict[str, Any]]) -> list[dict[str, Any]]:
    """Get unresolved blocking deps for a task. Returns list of blocking task dicts."""
    block_ids = _get_dep_ids(task, dep_type="blocks")
    blockers: list[dict[str, Any]] = []
    for bid in block_ids:
        target = _resolve_related(bid, tasks_list, closed_list)
        if target is None or (target.get("status") != "done" and not target.get("closed", False)):
            blockers.append({"id": bid, "task": target})
    return blockers


def _is_task_blocked(task: dict[str, Any], tasks_list: list[dict[str, Any]],
                     closed_list: list[dict[str, Any]]) -> bool:
    """Check if a task has any unresolved blocking deps."""
    return len(_get_blockers(task, tasks_list, closed_list)) > 0


def _collect_all_tags(tasks: list[dict[str, Any]]) -> dict[str, int]:
    """Count tag frequency across all given tasks."""
    counts: dict[str, int] = {}
    for t in tasks:
        for tag in t.get("tags", []) or []:
            counts[tag] = counts.get(tag, 0) + 1
    return dict(sorted(counts.items(), key=lambda x: x[1], reverse=True))


def _normalize_notes(notes: Any) -> list[str]:
    """Normalize notes to list[str]. Converts string to single-element list for backwards compat."""
    if notes is None:
        return []
    if isinstance(notes, str):
        return [notes]
    if isinstance(notes, list):
        return notes
    return [str(notes)]


def _inbox_line_count() -> int:
    """Return number of non-empty lines in inbox.md."""
    content = load_inbox()
    return len([line for line in content.splitlines() if line.strip()])


# ---------------------------------------------------------------------------
# Data operations
# ---------------------------------------------------------------------------


def init_task_files() -> dict[str, str]:
    """Bootstrap the tasks/ directory and three files. Idempotent.

    Returns a dict mapping file path -> action taken ('created' | 'exists').
    """
    tasks_dir = _resolve_tasks_dir()
    results: dict[str, str] = {}

    tasks_dir.mkdir(parents=True, exist_ok=True)

    # inbox.md
    inbox = _inbox_file()
    if not inbox.exists():
        inbox.write_text("", encoding="utf-8")
        results[str(inbox)] = "created"
    else:
        results[str(inbox)] = "exists"

# tasks.yaml
    tasks_file = _tasks_file()
    if not tasks_file.exists():
        data = {"meta": {"counter": 0}, "tasks": []}
        content = TASKS_HEADER + yaml.safe_dump(data, default_flow_style=False,
                                                 sort_keys=False, allow_unicode=True)
        tasks_file.write_text(content, encoding="utf-8")
        results[str(tasks_file)] = "created"
    else:
        # Validate existing file is parseable YAML
        try:
            load_tasks_yaml()
            results[str(tasks_file)] = "exists"
        except yaml.YAMLError:
            results[str(tasks_file)] = "invalid"
            return results

    # closed.yaml
    closed_file = _resolve_tasks_dir() / CLOSED_FILE_NAME
    if not closed_file.exists():
        # Check for old done.yaml to migrate
        old_done = _resolve_tasks_dir() / "done.yaml"
        if old_done.exists():
            # Rename old done.yaml to closed.yaml
            old_done.rename(closed_file)
            results[str(closed_file)] = "migrated from done.yaml"
        else:
            data = {"meta": {"total_closed": 0}, "tasks": []}
            content = CLOSED_HEADER + yaml.safe_dump(data, default_flow_style=False,
                                                      sort_keys=False, allow_unicode=True)
            closed_file.write_text(content, encoding="utf-8")
            results[str(closed_file)] = "created"
    else:
        results[str(closed_file)] = "exists"

    return results


def next_counter_and_id() -> tuple[int, str]:
    """Read meta.counter, increment it, save, and return (new_counter, formatted_id).

    Raises FileNotFoundError if tasks.yaml doesn't exist.
    """
    meta, tasks = load_tasks_yaml()
    counter = meta.get("counter", 0)
    if not isinstance(counter, int):
        counter = 0
    new_counter = counter + 1
    meta["counter"] = new_counter
    save_tasks_yaml(meta, tasks)
    return new_counter, _format_id(new_counter)


def add_task(title: str, priority: int | str | None = None,
             tags: list[str] | None = None,
             source: str | None = None,
             deps: list[dict[str, str]] | None = None,
             related: str | None = None,
             notes: str | None = None) -> dict[str, Any]:
    """Create a new task and prepend it to tasks.yaml.

    deps: list of {"id": "TSK-NNNN", "type": "<dep_type>"} dicts.
    related: legacy convenience — creates a "relates" dep entry if no deps given.

    Returns the created task dict.
    """
    meta, tasks = load_tasks_yaml()
    counter = meta.get("counter", 0)
    if not isinstance(counter, int):
        counter = 0
    new_counter = counter + 1
    meta["counter"] = new_counter
    task_id = _format_id(new_counter)

    task: dict[str, Any] = {
        "id": task_id,
        "title": title,
        "status": "todo",
        "created": _now_date(),
        "closed": False,
    }
    if priority is not None:
        norm_p = _normalize_priority(priority)
        if norm_p is not None:
            task["priority"] = norm_p
    if tags:
        task["tags"] = [t.lower().strip().replace(" ", "-") for t in tags]
    if source:
        task["source"] = source
    # Handle deps vs related
    if deps:
        task["deps"] = deps
    elif related:
        task["deps"] = [{"id": related, "type": "relates"}]
    if notes:
        # Store as list[str] — single string becomes one-element list
        task["notes"] = [notes]

    # Prepend: newest at top
    tasks.insert(0, task)
    save_tasks_yaml(meta, tasks)
    return task


def update_task(task_id: str, status: str | None = None,
                priority: int | str | None = None,
                tags: list[str] | None = None,
                deps: list[dict[str, str]] | None = None,
                related: str | None = None,
                notes: str | None = None, replace_notes: bool = False,
                closed: bool | None = None) -> dict[str, Any]:
    """Update fields on an existing task. Tags and deps are appended, not replaced.

    deps: list of {"id": "TSK-NNNN", "type": "<dep_type>"} dicts to append.
    related: legacy convenience — appends a "relates" dep entry.

    Returns the updated task dict.
    Raises ValueError if task not found.
    """
    meta, tasks = load_tasks_yaml()
    task = _find_task_by_id(tasks, task_id)
    if task is None:
        raise ValueError(f"Task not found: {task_id}")

    if status is not None:
        task["status"] = status
    if priority is not None:
        norm_p = _normalize_priority(priority)
        if norm_p is not None:
            task["priority"] = norm_p
    if tags is not None:
        existing = task.get("tags", []) or []
        new_tags = [t.lower().strip().replace(" ", "-") for t in tags]
        for tag in new_tags:
            if tag not in existing:
                existing.append(tag)
        task["tags"] = existing
    # Handle deps vs related — append, don't replace
    if deps:
        existing_deps = _ensure_deps_field(task)
        for dep in deps:
            dep_id = dep.get("id", "")
            dep_type = dep.get("type", "relates")
            # Avoid duplicates: same id + type
            if not any(d.get("id") == dep_id and d.get("type") == dep_type for d in existing_deps):
                existing_deps.append({"id": dep_id, "type": dep_type})
    elif related is not None:
        existing_deps = _ensure_deps_field(task)
        if not any(d.get("id") == related and d.get("type") == "relates" for d in existing_deps):
            existing_deps.append({"id": related, "type": "relates"})
    if notes is not None:
        existing = _normalize_notes(task.get("notes"))
        if replace_notes or not existing:
            # --replace-notes or no existing notes → set fresh list
            task["notes"] = [notes]
        else:
            # Default: append to existing list
            existing.append(notes)
            task["notes"] = existing

    if closed is True:
        task["closed"] = True
        task["closed_at"] = _now_iso()
    elif closed is False:
        task["closed"] = False

    task["updated"] = _now_iso()

    if closed is True:
        # Move to closed.yaml
        tasks.remove(task)
        save_tasks_yaml(meta, tasks)
        closed_list = load_closed_yaml()
        closed_list.append(task)
        save_closed_yaml(closed_list)
    else:
        save_tasks_yaml(meta, tasks)

    return task


def close_task(task_id: str, note: str | None = None) -> dict[str, Any]:
    """Move a task from tasks.yaml to closed.yaml. Preserves its status.

    Sets closed=True, adds 'closed_at' timestamp.
    Appends optional --note to the existing notes field.
    Returns the closed task dict.
    Raises ValueError if task not found or already closed.
    """
    meta, tasks = load_tasks_yaml()
    task = _find_task_by_id(tasks, task_id)
    if task is None:
        # Check if task is already closed
        closed_list = load_closed_yaml()
        closed_task = _find_task_by_id(closed_list, task_id)
        if closed_task is not None:
            raise ValueError(f"Task already closed: {task_id}")
        raise ValueError(f"Task not found: {task_id}")

    # Remove from active list
    tasks.remove(task)

    # Update the task — PRESERVE status, set closed flag
    task["closed"] = True
    task["closed_at"] = _now_iso()
    task["updated"] = _now_iso()
    if note:
        existing_notes = _normalize_notes(task.get("notes"))
        existing_notes.append(note)
        task["notes"] = existing_notes

    # Save active list
    save_tasks_yaml(meta, tasks)

    # Append to closed.yaml (oldest-first: append to bottom)
    closed_list = load_closed_yaml()
    closed_list.append(task)
    save_closed_yaml(closed_list)

    return task


def _task_has_dep_id(task: dict[str, Any], dep_id: str) -> bool:
    """Check if a task has a dep entry pointing to the given ID."""
    for dep in (task.get("deps") or []):
        if isinstance(dep, dict) and dep.get("id") == dep_id:
            return True
    # Also check legacy related field for backwards compat during migration
    if task.get("related") == dep_id:
        return True
    return False


def filter_tasks(tasks: list[dict[str, Any]], status: str | None = None,
                 tags: list[str] | None = None, tag: str | None = None,
                 tags_any: list[str] | None = None,
                 priority: int | str | None = None,
                 source: str | None = None, related: str | None = None) -> list[dict[str, Any]]:
    """Filter a task list by status, tags, priority, source, and/or related. All filters ANDed.

    tags: list of tags — task must contain ALL of them (AND logic).
    tags_any: list of tags — task must contain ANY of them (OR logic).
    priority: numeric or named alias.
    related: matches any dep entry with that ID (checks against 'deps' list).
    """
    result = tasks
    if status:
        result = [t for t in result if t.get("status") == status]
    if priority is not None:
        norm_p = _normalize_priority(priority)
        if norm_p is not None:
            result = [t for t in result if _normalize_priority(t.get("priority")) == norm_p]
    if source:
        result = [t for t in result if t.get("source") == source]
    if tag:
        tags = (tags or []) + [tag]
    if tags:
        for tag in tags:
            result = [t for t in result if tag in (t.get("tags") or [])]
    if tags_any:
        normalized_any = [t.lower().strip().replace(" ", "-") for t in tags_any]
        result = [t for t in result if any(tg in (t.get("tags") or []) for tg in normalized_any)]
    if related:
        result = [t for t in result if _task_has_dep_id(t, related)]
    return result


# ---------------------------------------------------------------------------
# Simple text search
# ---------------------------------------------------------------------------


def _task_text(task: dict[str, Any]) -> str:
    """Build a searchable text blob from a task (lowercased)."""
    parts: list[str] = [
        task.get("id", ""),
        task.get("title", ""),
        task.get("status", ""),
        str(task.get("priority", "")),
        task.get("source", ""),
        " ".join(task.get("tags", []) or []),
    ]
    # Add dep IDs and types to search text
    for dep in (task.get("deps") or []):
        if isinstance(dep, dict):
            parts.append(dep.get("id", ""))
            parts.append(dep.get("type", ""))
    # Also check legacy related field
    related = task.get("related")
    if related:
        parts.append(str(related))
    notes = task.get("notes")
    if notes:
        if isinstance(notes, list):
            parts.extend(str(n) for n in notes)
        else:
            parts.append(str(notes))
    return " ".join(parts).lower()


def search_tasks(tasks: list[dict], text: str) -> list[dict]:
    """Simple case-insensitive text search across all task fields."""
    needle = text.lower()
    return [t for t in tasks if needle in _task_text(t)]


# ---------------------------------------------------------------------------
# CLI
# ---------------------------------------------------------------------------

console = Console()


@click.group()
def main():
    """Lightweight task management for AI agents."""
    pass


# ---- init ----

@main.command()
def init():
    """Bootstrap task files in the current directory. Safe to run repeatedly."""
    results = init_task_files()
    for path, action in results.items():
        if action == "created":
            click.echo(f"  Created {path}")
        elif action == "invalid":
            click.echo(f"  Error: {path} exists but is invalid YAML. Delete it and re-run.", err=True)
            sys.exit(1)

    if all(v == "exists" for v in results.values()):
        click.echo("All files already exist. Nothing to do.")
    elif any(v == "created" for v in results.values()):
        click.echo("Task system initialized.")


# ---- add ----

def _parse_dep_option(dep_str: str) -> dict[str, str]:
    """Parse 'id:type' or just 'id' (defaults to relates type)."""
    if ":" in dep_str:
        parts = dep_str.split(":", 1)
        return {"id": parts[0], "type": parts[1]}
    return {"id": dep_str, "type": "relates"}


@main.command()
@click.argument("title")
@click.option("--tag", "-t", "tags", multiple=True, help="Tag(s) to apply (repeatable)")
@click.option("--priority", "-p", help="Priority: p0-p4, 0-4, or name (critical, urgent, high, medium, low, backlog)")
@click.option("--source", "-s", type=click.Choice(list(VALID_SOURCES)), default="agent", help="Source of the task")
@click.option("--dep", "deps", multiple=True, help="Dependency: id:type (e.g. TSK-0042:blocks, TSK-0017:relates)")
@click.option("--related", "-r", help="Related task ID (shorthand for --dep id:relates)")
@click.option("--notes", "-n", help="Freeform notes")
def add(title: str, tags: tuple[str, ...], priority: str | None, source: str,
        deps: tuple[str, ...], related: str | None, notes: str | None):
    """Create a new task. ID is auto-generated."""
    parsed_deps = [_parse_dep_option(d) for d in deps] if deps else None
    task = add_task(
        title=title,
        priority=priority,
        tags=list(tags) if tags else None,
        source=source,
        deps=parsed_deps,
        related=related,
        notes=notes,
    )
    click.echo(f"Created {task['id']}: {title}")


# ---- list ----

@main.command("list")
@click.option("--status", type=click.Choice(list(VALID_STATUSES)), help="Filter by status")
@click.option("--tag", "tags", multiple=True, help="Filter by tag (repeatable, AND logic)")
@click.option("--tag-any", "tags_any", multiple=True, help="Filter by tag (OR logic, repeatable)")
@click.option("--priority", help="Filter by priority (p0-p4, 0-4, or name like urgent, high)")
@click.option("--source", type=click.Choice(list(VALID_SOURCES)), help="Filter by source")
@click.option("--related", "-r", help="Filter by related/dep task ID")
@click.option("--text", "-t", help="Full-text search (combined with other filters)")
@click.option("--json", "json_output", is_flag=True, help="Output as JSON")
def list_cmd(status: str | None, tags: tuple[str, ...], tags_any: tuple[str, ...],
             priority: str | None,
             source: str | None, related: str | None, text: str | None,
             json_output: bool):
    """List active tasks (not done). Newest first.

    \b
      tasks list --status todo
      tasks list --tag bug --tag auth
      tasks list --tag-any bug --tag-any security
      tasks list --related TSK-0001
      tasks list --text "login"
      tasks list --priority 1
    """
    try:
        _, tasks = load_tasks_yaml()
    except FileNotFoundError as e:
        click.echo(str(e), err=True)
        sys.exit(1)

    tasks = [t for t in tasks if not t.get("closed", False)]
    tasks = filter_tasks(tasks, status=status,
                         tags=list(tags) if tags else None,
                         tags_any=list(tags_any) if tags_any else None,
                         priority=priority, source=source, related=related)

    if text:
        tasks = search_tasks(tasks, text)

    if json_output:
        click.echo(__import__("json").dumps(tasks, indent=2))
        return

    if not tasks:
        click.echo("No tasks found.")
        return

    table = Table(title="Tasks")
    table.add_column("ID", style="cyan")
    table.add_column("Status", style="yellow")
    table.add_column("Priority", style="magenta")
    table.add_column("Title", style="white")
    table.add_column("Tags", style="green")

    for t in tasks:
        table.add_row(
            t.get("id", "?"),
            t.get("status", "?"),
            _format_priority(t.get("priority")),
            t.get("title", "?"),
            ", ".join(t.get("tags", []) or []),
        )

    console.print(table)


# ---- show ----

@main.command()
@click.argument("task_id")
def show(task_id: str):
    """Show full detail of one task. Resolves related task inline."""
    try:
        _, tasks = load_tasks_yaml()
        closed_list = load_closed_yaml()
    except FileNotFoundError as e:
        click.echo(str(e), err=True)
        sys.exit(1)

    task = _find_task_by_id(tasks, task_id)
    if task is None:
        task = _find_task_by_id(closed_list, task_id)
    if task is None:
        click.echo(f"Task not found: {task_id}", err=True)
        sys.exit(1)

    click.echo(f"\n  [{task.get('id')}] {task.get('status')}  priority: {_format_priority(task.get('priority'))}")
    click.echo(f"  {task.get('title')}")

    tags = task.get("tags")
    if tags:
        click.echo(f"  tags: {', '.join(tags)}")

    if task.get("source"):
        src = task["source"]
        if task.get("source_ref"):
            src += f" ({task['source_ref']})"
        click.echo(f"  source: {src}")

    # Show deps inline
    deps = task.get("deps")
    if deps:
        for dep in deps:
            if not isinstance(dep, dict):
                continue
            dep_id = dep.get("id", "")
            dep_type = dep.get("type", "relates")
            target = _resolve_related(dep_id, tasks, closed_list)
            if target:
                click.echo(f"  dep ({dep_type}): {dep_id} ({target.get('status')}) — \"{target.get('title')}\"")
            else:
                click.echo(f"  dep ({dep_type}): {dep_id} (not found)")
    # Legacy related fallback
    elif task.get("related"):
        related_id = task["related"]
        target = _resolve_related(related_id, tasks, closed_list)
        if target:
            click.echo(f"  related: {related_id} ({target.get('status')}) — \"{target.get('title')}\"")
        else:
            click.echo(f"  related: {related_id} (not found)")

    click.echo(f"  created: {task.get('created')}")
    if task.get("updated"):
        click.echo(f"  updated: {task.get('updated')}")
    if task.get("closed_at"):
        click.echo(f"  closed_at: {task.get('closed_at')}")
    elif task.get("completed"):
        click.echo(f"  completed: {task.get('completed')}")
    notes_val = task.get("notes")
    if notes_val:
        notes_list = _normalize_notes(notes_val)
        if len(notes_list) == 1:
            click.echo(f"  notes: {notes_list[0]}")
        else:
            click.echo("  notes:")
            for i, note in enumerate(notes_list, 1):
                click.echo(f"    {i}. {note}")
    click.echo("")


# ---- update ----

@main.command()
@click.argument("task_id")
@click.option("--status", type=click.Choice(list(VALID_STATUSES)), help="Change status")
@click.option("--tag", "-t", "tags", multiple=True, help="Tag(s) to append (repeatable)")
@click.option("--priority", "-p", help="Change priority (p0-p4, 0-4, or name like urgent, high)")
@click.option("--dep", "deps", multiple=True, help="Append dependency: id:type (repeatable)")
@click.option("--related", "-r", help="Set related task ID (shorthand for --dep id:relates)")
@click.option("--notes", "-n", help="Append a note (use --replace-notes to overwrite)")
@click.option("--replace-notes", is_flag=True, help="Replace notes instead of appending")
@click.option("--closed", "-c", is_flag=True, help="Close the task (move to closed.yaml)")
def update(task_id: str, status: str | None, tags: tuple[str, ...], priority: str | None,
           deps: tuple[str, ...], related: str | None, notes: str | None,
           replace_notes: bool, closed: bool):
    """Update fields on a task. Tags and deps are appended to existing."""
    parsed_deps = [_parse_dep_option(d) for d in deps] if deps else None
    try:
        task = update_task(
            task_id=task_id,
            status=status,
            priority=priority,
            tags=list(tags) if tags else None,
            deps=parsed_deps,
            related=related,
            notes=notes,
            replace_notes=replace_notes,
            closed=closed if closed else None,
        )
        click.echo(f"Updated {task['id']}: {task['title']}")
    except FileNotFoundError as e:
        click.echo(str(e), err=True)
        sys.exit(1)
    except ValueError as e:
        click.echo(str(e), err=True)
        sys.exit(1)


# ---- close ----

@main.command()
@click.argument("task_id")
@click.option("--note", "-n", help="Closing note to append")
def close(task_id: str, note: str | None):
    """Close a task. Moves it to closed.yaml, preserves its status.

    The task's status is NOT changed — only the 'closed' flag is set.
    Use 'tasks update --status <name> --closed' to set status and close at once.
    """
    try:
        task = close_task(task_id, note=note)
        click.echo(f"Closed {task['id']}: {task['title']} (status: {task.get('status', '?')})")
    except FileNotFoundError as e:
        click.echo(str(e), err=True)
        sys.exit(1)
    except ValueError as e:
        click.echo(str(e), err=True)
        sys.exit(1)


# ---- next ----

@main.command()
@click.option("--take", default="1", help="Number of tasks, or 'all'")
@click.option("--tag", help="Filter by tag")
@click.option("--priority", help="Filter by priority (0-4 or name)")
@click.option("--skip-related", is_flag=True, help="Exclude tasks whose deps (type=blocks) are not resolved")
@click.option("--skip-blocks", is_flag=True, help="Alias for --skip-related")
def next_cmd(take: str, tag: str | None, priority: str | None,
             skip_related: bool, skip_blocks: bool):
    """Show highest-priority todo task(s)."""
    try:
        _, tasks = load_tasks_yaml()
        closed_list = load_closed_yaml()
    except FileNotFoundError as e:
        click.echo(str(e), err=True)
        sys.exit(1)

    # Filter to todo only
    candidates = [t for t in tasks if t.get("status") == "todo"]
    # Exclude closed tasks
    candidates = [t for t in candidates if not t.get("closed", False)]
    candidates = filter_tasks(
        candidates,
        tags=[tag] if tag else None,
        priority=priority,
    )

    # --skip-related / --skip-blocks: exclude tasks with unresolved blocking deps
    skip = skip_related or skip_blocks
    if skip:
        candidates = [t for t in candidates if not _is_task_blocked(t, tasks, closed_list)]

    # Sort by priority (highest first), then newest first
    candidates.sort(key=lambda t: t.get("created", ""), reverse=True)  # newest first
    candidates.sort(key=_priority_sort_key)  # stable sort by priority (lower=higher)

    # Take
    if take == "all":
        count = len(candidates)
    else:
        try:
            count = int(take)
        except ValueError:
            click.echo(f"Invalid --take value: {take}. Use a number or 'all'.", err=True)
            sys.exit(1)

    results = candidates[:count]

    if not results:
        click.echo("No tasks found.")
        return

    for t in results:
        tags_str = ", ".join(t.get("tags", []) or [])
        click.echo(f"  [{t.get('id')}] {_format_priority(t.get('priority')):4s}  {t.get('title')}  tags: {tags_str}")


# ---- status ----

@main.command()
@click.option("--json", "json_output", is_flag=True, help="Output as JSON")
def status(json_output: bool):
    """Show session overview: in-progress, top priorities, tag stats, inbox status."""
    try:
        _, tasks = load_tasks_yaml()
    except FileNotFoundError as e:
        click.echo(str(e), err=True)
        sys.exit(1)

    active = [t for t in tasks if not t.get("closed", False)]
    in_progress = [t for t in active if t.get("status") == "in-progress"]
    todo = [t for t in active if t.get("status") == "todo"]

    # Top priority: sort by priority then created desc
    top_todo = sorted(todo, key=lambda t: t.get("created", ""), reverse=True)
    top_todo.sort(key=_priority_sort_key)
    top_todo = top_todo[:5]

    tag_counts = _collect_all_tags(active)
    inbox_count = _inbox_line_count()

    if json_output:
        import json as _json
        output = {
            "counts": {
                "todo": len(todo),
                "in_progress": len(in_progress),
            },
            "in_progress": in_progress,
            "top_priority": top_todo,
            "tags": tag_counts,
            "inbox_entries": inbox_count,
        }
        click.echo(_json.dumps(output, indent=2))
        return

    click.echo(f"\nTasks: {len(in_progress)} in-progress, {len(todo)} todo")

    if in_progress:
        click.echo("\nIN PROGRESS")
        for t in in_progress:
            tags_str = ", ".join(t.get("tags", []) or [])
            click.echo(f"  [{t.get('id')}] {_format_priority(t.get('priority')):4s}  {t.get('title')}  tags: {tags_str}")

    if top_todo:
        click.echo("\nTOP PRIORITY")
        for t in top_todo:
            tags_str = ", ".join(t.get("tags", []) or [])
            click.echo(f"  [{t.get('id')}] {_format_priority(t.get('priority')):4s}  {t.get('title')}  tags: {tags_str}")
    else:
        click.echo("\nNo pending tasks.")

    if tag_counts:
        tags_line = ", ".join(f"{k}({v})" for k, v in list(tag_counts.items())[:10])
        click.echo(f"\nTAGS: {tags_line}")

    if inbox_count:
        click.echo(f"\nInbox has {inbox_count} unprocessed entries. Run `tasks inbox` to view.")
    click.echo("")


# ---- history ----

@main.command()
@click.option("--tag", "tags", multiple=True, help="Filter by tag (repeatable, AND logic)")
@click.option("--tag-any", "tags_any", multiple=True, help="Filter by tag (OR logic, repeatable)")
@click.option("--text", help="Full-text search within closed tasks")
@click.option("--related", "-r", help="Filter by related task ID")
@click.option("--limit", default="30", help="Number of tasks to show, or 'all' (default: 30)")
@click.option("--offset", default=0, type=int, help="Skip N entries from the newest (default: 0)")
@click.option("--json", "json_output", is_flag=True, help="Output as JSON")
def history(tags: tuple[str, ...], tags_any: tuple[str, ...], text: str | None,
            related: str | None,
            limit: str, offset: int, json_output: bool):
    """Show recently closed tasks (newest first). Default limit: 30.

    Use --limit all to show everything. Use --offset N to page through results.
    """
    closed_list = load_closed_yaml()

    closed_list = filter_tasks(closed_list,
                               tags=list(tags) if tags else None,
                               tags_any=list(tags_any) if tags_any else None,
                               related=related)

    if text:
        closed_list = search_tasks(closed_list, text)

    total = len(closed_list)

    # closed.yaml is oldest-first; reverse for display (newest first)
    closed_list = list(reversed(closed_list))

    # Apply offset
    closed_list = closed_list[offset:]

    # Apply limit
    if limit == "all":
        count = len(closed_list)
    else:
        try:
            count = int(limit)
        except ValueError:
            click.echo(f"Invalid --limit value: {limit}. Use a number or 'all'.", err=True)
            sys.exit(1)
        count = min(count, len(closed_list))

    display = closed_list[:count]

    if json_output:
        click.echo(__import__("json").dumps(display, indent=2))
        return

    if not display:
        click.echo("No completed tasks.")
        return

    table = Table(title="Completed Tasks")
    table.add_column("ID", style="cyan")
    table.add_column("Priority", style="magenta")
    table.add_column("Title", style="white")
    table.add_column("Completed", style="green")
    table.add_column("Tags", style="dim")

    for t in display:
        completed_val = t.get("closed_at") or t.get("completed") or ""
        completed_display = completed_val[:10] if completed_val else "?"
        table.add_row(
            t.get("id", "?"),
            _format_priority(t.get("priority")),
            t.get("title", "?"),
            completed_display,
            ", ".join(t.get("tags", []) or []),
        )

    console.print(table)

    # Pagination hint when there are more results available
    remaining = total - offset - len(display)
    if remaining > 0:
        shown = offset + len(display)
        console.print(f"\n[dim]Showing {shown} of {total}. "
                      f"Use --offset {shown} to see next page, "
                      f"--limit all to see everything.[/dim]")


# ---- inbox ----

@main.command()
def inbox():
    """Print inbox.md contents."""
    content = load_inbox()
    if content.strip():
        click.echo(content)
    else:
        click.echo("Inbox is empty.")


# ---- search ----

@main.command()
@click.argument("text")
@click.option("--in", "search_field", help="Scope search to a specific field (title, notes, id, status, priority, tags, source)")
@click.option("--json", "json_output", is_flag=True, help="Output as JSON")
def search(text: str, search_field: str | None, json_output: bool):
    """Full-text search across ALL tasks (active + closed).

    \b
    Examples:
      tasks search login
      tasks search bug
      tasks search "dark mode"
      tasks search login --in title
      tasks search "auth" --in notes
    """
    try:
        _, tasks = load_tasks_yaml()
        closed_list = load_closed_yaml()
    except FileNotFoundError as e:
        click.echo(str(e), err=True)
        sys.exit(1)

    # Merge active + closed, deduplicating by id
    all_tasks: list[dict] = list(tasks)
    active_ids = {t.get("id") for t in all_tasks}
    for ct in closed_list:
        if ct.get("id") not in active_ids:
            all_tasks.append(ct)

    if search_field:
        # Field-scoped search
        needle = text.lower()
        results = []
        for t in all_tasks:
            val = t.get(search_field)
            if val is None:
                continue
            if isinstance(val, list):
                val_str = " ".join(str(v) for v in val).lower()
            else:
                val_str = str(val).lower()
            if needle in val_str:
                results.append(t)
    else:
        results = search_tasks(all_tasks, text)

    if json_output:
        click.echo(__import__("json").dumps(results, indent=2))
        return

    if not results:
        click.echo("No results found.")
        return

    table = Table(title=f"Search: {text}")
    table.add_column("ID", style="cyan")
    table.add_column("Status", style="yellow")
    table.add_column("Priority", style="magenta")
    table.add_column("Title", style="white")
    table.add_column("Tags", style="green")
    table.add_column("Source", style="dim")

    for t in results:
        table.add_row(
            t.get("id", "?"),
            t.get("status", "?"),
            _format_priority(t.get("priority")),
            t.get("title", "?"),
            ", ".join(t.get("tags", []) or []),
            t.get("source", "-"),
        )

    console.print(table)


# ---- deps ----

@main.command()
@click.argument("task_id")
def deps(task_id: str):
    """Show dependency graph for a task (both directions)."""
    try:
        _, tasks = load_tasks_yaml()
        closed_list = load_closed_yaml()
    except FileNotFoundError as e:
        click.echo(str(e), err=True)
        sys.exit(1)

    task = _find_task_by_id(tasks, task_id)
    if task is None:
        task = _find_task_by_id(closed_list, task_id)
    if task is None:
        click.echo(f"Task not found: {task_id}", err=True)
        sys.exit(1)

    click.echo(f"\n  [{task.get('id')}] {task.get('title')}")

    # Show deps this task has (outgoing)
    out_deps = task.get("deps") or []
    if out_deps:
        click.echo("\n  DEPENDS ON:")
        for dep in out_deps:
            if not isinstance(dep, dict):
                continue
            dep_id = dep.get("id", "")
            dep_type = dep.get("type", "relates")
            target = _resolve_related(dep_id, tasks, closed_list)
            if target:
                status_str = target.get("status", "?")
                click.echo(f"    {dep_id} ({dep_type}) [{status_str}] — {target.get('title')}")
            else:
                click.echo(f"    {dep_id} ({dep_type}) [not found]")

    # Show tasks that depend on this one (incoming)
    incoming: list[tuple[str, str, str]] = []  # (dep_id, dep_type, title)
    for t in tasks + closed_list:
        for dep in (t.get("deps") or []):
            if isinstance(dep, dict) and dep.get("id") == task_id:
                incoming.append((t.get("id", "?"), dep.get("type", "?"), t.get("title", "?")))
                break  # one entry per dependent task
    if incoming:
        click.echo("\n  DEPENDED BY:")
        for dep_id, dep_type, title in incoming:
            click.echo(f"    {dep_id} ({dep_type}) — {title}")

    if not out_deps and not incoming:
        click.echo("  No dependencies.")
    click.echo("")


# ---- ready ----

@main.command()
@click.option("--take", default="5", help="Number of tasks, or 'all'")
@click.option("--tag", help="Filter by tag")
@click.option("--json", "json_output", is_flag=True, help="Output as JSON")
def ready(take: str, tag: str | None, json_output: bool):
    """Show top-priority unblocked todo tasks.

    Excludes tasks whose blocks-type deps are not yet done/closed.
    Sorted by priority (p0 first), then newest first.
    """
    try:
        _, tasks = load_tasks_yaml()
        closed_list = load_closed_yaml()
    except FileNotFoundError as e:
        click.echo(str(e), err=True)
        sys.exit(1)

    # Filter to todo, not closed, not blocked
    candidates = [
        t for t in tasks
        if t.get("status") == "todo"
        and not t.get("closed", False)
        and not _is_task_blocked(t, tasks, closed_list)
    ]

    if tag:
        candidates = [t for t in candidates if tag in (t.get("tags") or [])]

    # Sort by priority, then newest first
    candidates.sort(key=lambda t: t.get("created", ""), reverse=True)
    candidates.sort(key=_priority_sort_key)

    # Take
    if take == "all":
        count = len(candidates)
    else:
        try:
            count = int(take)
        except ValueError:
            click.echo(f"Invalid --take value: {take}. Use a number or 'all'.", err=True)
            sys.exit(1)

    results = candidates[:count]

    if json_output:
        click.echo(__import__("json").dumps(results, indent=2))
        return

    if not results:
        click.echo("No ready tasks. Check 'tasks blocked' or 'tasks next' for the full queue.")
        return

    click.echo(f"\nREADY ({len(results)}):")
    for t in results:
        tags_str = ", ".join(t.get("tags", []) or [])
        click.echo(f"  [{t.get('id')}] {_format_priority(t.get('priority')):4s}  {t.get('title')}  tags: {tags_str}")
    click.echo("")


# ---- blocked ----

@main.command()
@click.option("--json", "json_output", is_flag=True, help="Output as JSON")
def blocked(json_output: bool):
    """Show tasks that are blocked by unresolved deps.

    Lists what's blocking each task and the blocker's current status.
    """
    try:
        _, tasks = load_tasks_yaml()
        closed_list = load_closed_yaml()
    except FileNotFoundError as e:
        click.echo(str(e), err=True)
        sys.exit(1)

    # Find active (not closed) tasks with unresolved blocks deps
    candidates = [
        t for t in tasks
        if not t.get("closed", False)
        and _is_task_blocked(t, tasks, closed_list)
    ]

    if json_output:
        output = []
        for t in candidates:
            blockers = _get_blockers(t, tasks, closed_list)
            entry = dict(t)
            entry["blockers"] = [
                {"id": b["id"], "status": b["task"].get("status") if b["task"] else "not_found",
                 "title": b["task"].get("title") if b["task"] else None}
                for b in blockers
            ]
            output.append(entry)
        click.echo(__import__("json").dumps(output, indent=2))
        return

    if not candidates:
        click.echo("\nNo blocked tasks. Everything's ready to go! 🎉\n")
        return

    click.echo(f"\nBLOCKED ({len(candidates)}):")
    for t in candidates:
        blockers = _get_blockers(t, tasks, closed_list)
        tags_str = ", ".join(t.get("tags", []) or [])
        click.echo(f"\n  [{t.get('id')}] {_format_priority(t.get('priority')):4s} {t.get('title')}  tags: {tags_str}")
        for b in blockers:
            b_task = b["task"]
            if b_task:
                click.echo(f"    ⛔ blocked by {b['id']} ({b_task.get('status')}) — {b_task.get('title')}")
            else:
                click.echo(f"    ⛔ blocked by {b['id']} (not found)")
    click.echo("")


if __name__ == "__main__":
    main()
